server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/adso_product
    username: postgres
    password: b3192621119B
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      platform: postgresql
jwt:
  secret: ${KEYSECRET_SECURITY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IlBvd2VyIFVwIEZ1bGwgU3RhY2siLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNTE2MjM5MDIyfQ.8r-71aFvp9lUbJHbUQnkHTYzlfZsdeF5n2ZZedqgee4}
  expiration: ${EXPIRE_DAYS_SECURITY:3600000}
